apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypalsv-deployment
  labels:
    app: paypalsv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paypalsv
  template:
    metadata:
      labels:
        app: paypalsv

    spec:
      containers:
        - name: paypalsv
          image: sarose301/paypalsv:latest
          ports:
            - containerPort: 8087
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: paypalsv-config
                  key: someKey1
            - name: ORDER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: paypalsv-config
                  key: orderService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: paypalsv-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: paypalsv-db

            - name: MYSQL_SCHEMA
              value: paypalsv_db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "3306"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paypalsv-secrets
                  key: mysql-root-password
