apiVersion: apps/v1
kind: Deployment
metadata:
  name: paysv-deployment
  labels:
    app: paysv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paysv
  template:
    metadata:
      labels:
        app: paysv

    spec:
      containers:
        - name: paysv
          image: sarose301/paysv:latest
          ports:
            - containerPort: 8084
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: paysv-config
                  key: someKey1
            - name: BANK_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: paysv-config
                  key: bankService
            - name: CC_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: paysv-config
                  key: ccService
            - name: PAYPAL_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: paysv-config
                  key: paypalService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: paysv-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: paysv-db

            - name: MYSQL_SCHEMA
              value: pay_db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "3306"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paysv-secrets
                  key: mysql-root-password
