apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsv-deployment
  labels:
    app: productsv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productsv
  template:
    metadata:
      labels:
        app: productsv

    spec:
      containers:
        - name: productsv
          image: sarose301/productsv:latest
          ports:
            - containerPort: 8081
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: productsv-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: productsv-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: productsv-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: productsv-db

            - name: MYSQL_SCHEMA
              value: productsv_db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "3306"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: productsv-secrets
                  key: mysql-root-password
